package com.demo.entities;
// Generated Nov 9, 2018 10:23:40 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Membership generated by hbm2java
 */
@Entity
@Table(name = "membership", catalog = "multivendor")
public class Membership implements java.io.Serializable {

	private Integer id;
	private String packageMember;
	private int duration;
	private int price;
	private Date dateCreated;
	private Date dateEnd;
	private Set<Shop> shops = new HashSet<Shop>(0);

	public Membership() {
	}

	public Membership(String packageMember, int duration, int price) {
		this.packageMember = packageMember;
		this.duration = duration;
		this.price = price;
	}

	public Membership(String packageMember, int duration, int price, Date dateCreated, Date dateEnd, Set<Shop> shops) {
		this.packageMember = packageMember;
		this.duration = duration;
		this.price = price;
		this.dateCreated = dateCreated;
		this.dateEnd = dateEnd;
		this.shops = shops;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "package_member", nullable = false, length = 250)
	public String getPackageMember() {
		return this.packageMember;
	}

	public void setPackageMember(String packageMember) {
		this.packageMember = packageMember;
	}

	@Column(name = "duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_Created", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_End", length = 19)
	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membership")
	public Set<Shop> getShops() {
		return this.shops;
	}

	public void setShops(Set<Shop> shops) {
		this.shops = shops;
	}

}
