package com.demo.entities;
// Generated Nov 2, 2018 11:27:01 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderdetail generated by hbm2java
 */
@Entity
@Table(name = "orderdetail", catalog = "multivendor")
public class Orderdetail implements java.io.Serializable {

	private OrderdetailId id;
	private Orders orders;
	private Product product;
	private int quantity;
	private Double price;
	private String status;
	
	
	public Orderdetail(OrderdetailId id, Orders orders, Product product, int quantity, Double price, String status) {
		super();
		this.id = id;
		this.orders = orders;
		this.product = product;
		this.quantity = quantity;
		this.price = price;
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Orderdetail() {
	}

	public Orderdetail(OrderdetailId id, Orders orders, Product product, int quantity) {
		this.id = id;
		this.orders = orders;
		this.product = product;
		this.quantity = quantity;
	}

	public Orderdetail(OrderdetailId id, Orders orders, Product product, int quantity, Double price) {
		this.id = id;
		this.orders = orders;
		this.product = product;
		this.quantity = quantity;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ordersId", column = @Column(name = "ordersId", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false)) })
	public OrderdetailId getId() {
		return this.id;
	}

	public void setId(OrderdetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordersId", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
