package com.demo.entities;
// Generated Nov 2, 2018 11:51:08 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "multivendor")
public class Orders implements java.io.Serializable {

	private Integer id;
	private User user;
	private String paymentMethod;
	private Date dateCreated;
	private Boolean status;
	private String name;
	private int confirmNumber;
	private Set<Orderdetail> orderdetails = new HashSet<Orderdetail>(0);

	public Orders() {
	}

	public Orders(User user, String paymentMethod, Date dateCreated, Boolean status, String name, int confirmNumber) {
		this.user = user;
		this.paymentMethod = paymentMethod;
		this.dateCreated = dateCreated;
		this.status = status;
		this.name = name;
		this.confirmNumber = confirmNumber;
	}

	public Orders(User user, String paymentMethod, Date dateCreated, Boolean status, String name, int confirmNumber,
			Set<Orderdetail> orderdetails) {
		this.user = user;
		this.paymentMethod = paymentMethod;
		this.dateCreated = dateCreated;
		this.status = status;
		this.name = name;
		this.confirmNumber = confirmNumber;
		this.orderdetails = orderdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "payment_method", nullable = false, length = 250)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_Created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "status", nullable = false)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "confirm_number", nullable = false)
	public int getConfirmNumber() {
		return this.confirmNumber;
	}

	public void setConfirmNumber(int confirmNumber) {
		this.confirmNumber = confirmNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<Orderdetail> getOrderdetails() {
		return this.orderdetails;
	}

	public void setOrderdetails(Set<Orderdetail> orderdetails) {
		this.orderdetails = orderdetails;
	}

}
