package com.demo.entities;
// Generated Nov 2, 2018 11:27:01 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Roleforuser generated by hbm2java
 */
@Entity
@Table(name = "roleforuser", catalog = "multivendor")
public class Roleforuser implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<User> users = new HashSet<User>(0);
	private Set<Shop> shops = new HashSet<Shop>(0);

	public Roleforuser() {
	}

	public Roleforuser(String name) {
		this.name = name;
	}

	public Roleforuser(String name, Set<User> users, Set<Shop> shops) {
		this.name = name;
		this.users = users;
		this.shops = shops;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_role", catalog = "multivendor", joinColumns = {
			@JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "shop_role", catalog = "multivendor", joinColumns = {
			@JoinColumn(name = "roleid", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "shopid", nullable = false, updatable = false) })
	public Set<Shop> getShops() {
		return this.shops;
	}

	public void setShops(Set<Shop> shops) {
		this.shops = shops;
	}

}
